# Generated by Django 3.0.8 on 2020-07-31 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, unique=True)),
                ('description', models.CharField(default='', max_length=200)),
                ('population', models.IntegerField()),
                ('gdp', models.FloatField(default='')),
            ],
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, unique=True)),
                ('description', models.CharField(default='', max_length=200)),
                ('population', models.IntegerField()),
                ('gdp', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=70, unique=True)),
                ('description', models.CharField(default='', max_length=200)),
                ('population', models.IntegerField()),
                ('gdp', models.FloatField(default='')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_api.Country')),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(default='', max_length=70, unique=True)),
                ('mname', models.CharField(default='', max_length=70, unique=True)),
                ('lname', models.CharField(default='', max_length=70, unique=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_api.City')),
            ],
        ),
        migrations.AddField(
            model_name='city',
            name='state',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='django_rest_api.State'),
        ),
    ]
